runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 100
network:
  instance_ip_mode: internal
  name: private-network
  subnetwork_name: us-central
  forwarded_ports: